### ISSUE TITLE
a is not a function

### ISSUE THREAD

**Issue by shukii** [0no-co/wonka#112]
I'm running wonka within my application, and occasionally this error pops up and crashes my app running locally:

```
////node_modules/wonka/dist/wonka.js:608
          c.forEach(function (c) {
            ^
TypeError: a is not a function
    at ////node_modules/@urql/core/src/exchanges/fetch.ts:36:17
    at ////node_modules/wonka/dist/wonka.js:167:16
    at ////node_modules/wonka/dist/wonka.js:482:60
    at ////node_modules/wonka/dist/wonka.js:609:13
    at Array.forEach (<anonymous>)
    at b (////node_modules/wonka/dist/wonka.js:608:13)
    at ////node_modules/wonka/dist/wonka.js:1146:42
    at ////node_modules/wonka/dist/wonka.js:630:31
    at ////node_modules/wonka/dist/wonka.js:180:49
    at h (////node_modules/wonka/dist/wonka.js:163:57)
```

I saw a similar issue [here](https://github.com/kitten/wonka/issues/108), however I believe we are using suspense

Any help would be greatly appreciated, as it is causing a bad developer experience

Thanks

**Comment by shukii** [comment]
@kitten any ideas?

**Comment by kitten** [comment]
Without a reproduction there's not much I can do. Unless you're using Wonka independently though, this is more of a question to post ok the urql repo. On the other hand though, the caveat here is that it must be an issue with the build process or repo itself you may have inadvertently caused here.

However, since the stacktrace here doesn't include call sites, code, and isn't pointing at the correct line even, I can't even guess what's going on 😅

**Comment by shukii** [comment]
Any luck with this @kitten? We're still facing it a year later and didn't get the answer from the other repo

**Comment by kitten** [comment]
@shukii Not sure when why this is happening but I'm preparing the repository to move over to TypeScript. urql will move over with the next major bump which will also ditch IE11 support and target ES2015 only.

I've tried this out, and if your environment is set up for it correctly, you should now get full sourcemaps on Wonka. So, potentially, a much easier time debugging.

That said, without a reproduction I can't help you here further myself. This is likely caused by a faulty exchange, faulty usage that shouldn't pass type checks, or an old version/bug that's fixed already 😅
